import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for AI Digest.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f4f4f8] text-[#14141e]">

      {/* ── NAV ── */}
      <nav className="sticky top-0 z-50 bg-[#f4f4f8]/90 backdrop-blur border-b border-black/[0.06] px-5 py-4 flex items-center justify-between">
        <Link href="/" className="font-bold text-base tracking-tight text-[#14141e]">
          AI Digest
        </Link>
      </nav>

      <main className="max-w-2xl mx-auto px-5 py-16">
        <h1 className="text-3xl font-bold text-[#14141e] mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-12">Last updated: May 2025</p>

        <div className="space-y-10 text-sm text-gray-600 leading-relaxed">

          <section>
            <h2 className="text-base font-semibold text-[#14141e] mb-3">1. What AI Digest is</h2>
            <p>
              AI Digest is a free service that fetches newly published arXiv papers, scores their
              relevance to your stated interests using OpenAI&apos;s API, and writes personalised
              summaries to a Notion database you control. By creating an account or using the
              service you agree to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#14141e] mb-3">2. Eligibility</h2>
            <ul className="list-disc list-inside space-y-2">
              <li>You must be at least 18 years old to use AI Digest.</li>
              <li>
                You may only create one account per person. Creating multiple accounts to
                circumvent usage limits (e.g. the daily pipeline run cap) is not permitted.
              </li>
              <li>
                Use is limited to individual, non-commercial research and learning purposes.
                You may not use AI Digest to build a competing service, resell digests, or
                systematically scrape its outputs.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#14141e] mb-3">3. Acceptable use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>Attempt to circumvent rate limits, account limits, or other access controls.</li>
              <li>
                Use the service to generate, distribute, or store unlawful, harmful, or
                abusive content.
              </li>
              <li>
                Reverse-engineer, scrape, or automate access to the service outside of its
                intended UI and API endpoints.
              </li>
              <li>
                Share your Notion integration token or account credentials with others or use
                another person&apos;s credentials without authorisation.
              </li>
              <li>
                Attempt to interfere with the service&apos;s infrastructure, including the arXiv
                fetching pipeline, Supabase database, or GitHub Actions workflows.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#14141e] mb-3">
              4. AI-generated content — no warranty
            </h2>
            <p className="mb-3">
              Digest summaries, relevance scores, and &quot;Builder Takeaway&quot; sections are
              generated by OpenAI&apos;s GPT-4o-mini model.{" "}
              <span className="font-medium text-[#14141e]">
                AI-generated content can be inaccurate, incomplete, or misleading.
              </span>
            </p>
            <ul className="list-disc list-inside space-y-2">
              <li>
                Summaries are provided for informational convenience only. Always read the
                original arXiv paper before acting on any finding.
              </li>
              <li>
                AI Digest makes no representations about the accuracy, completeness, or
                fitness for any particular purpose of the generated summaries.
              </li>
              <li>
                Do not rely solely on AI Digest summaries for academic, commercial, medical,
                legal, or safety-critical decisions.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#14141e] mb-3">5. Service availability</h2>
            <p>
              AI Digest is provided free of charge and on a best-effort basis. We do not
              guarantee uninterrupted delivery, a specific number of papers per digest,
              or that the service will remain available indefinitely. Scheduled deliveries
              depend on arXiv&apos;s API, OpenAI&apos;s API, Notion&apos;s API, and GitHub Actions —
              all of which are outside our control and may experience outages.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#14141e] mb-3">
              6. Termination &amp; suspension
            </h2>
            <p className="mb-3">
              We reserve the right to suspend or permanently terminate any account, with or
              without notice, for:
            </p>
            <ul className="list-disc list-inside space-y-2">
              <li>Violation of these terms, including circumventing usage limits.</li>
              <li>Any activity that places unreasonable load on the service or its costs.</li>
              <li>Any conduct we reasonably believe to be abusive or harmful.</li>
            </ul>
            <p className="mt-3">
              You may close your account at any time. On closure, all your data is permanently
              deleted as described in our{" "}
              <Link href="/privacy" className="text-indigo-600 hover:underline">
                Privacy Policy
              </Link>
              .
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#14141e] mb-3">
              7. Limitation of liability
            </h2>
            <p>
              To the fullest extent permitted by applicable law, AI Digest and its operators
              are not liable for any indirect, incidental, special, or consequential damages
              arising from your use of — or inability to use — the service. This includes,
              without limitation, missed paper deliveries, incorrect AI summaries, data loss,
              Notion API errors, or third-party service outages.
            </p>
            <p className="mt-3">
              The service is provided{" "}
              <span className="font-medium text-[#14141e]">&quot;as is&quot;</span> and{" "}
              <span className="font-medium text-[#14141e]">&quot;as available&quot;</span>, without
              warranty of any kind, express or implied.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#14141e] mb-3">
              8. Third-party services
            </h2>
            <p>
              AI Digest relies on Notion, OpenAI, arXiv, Clerk, and Supabase. Your use of
              those services is also governed by their respective terms of service. We are not
              responsible for changes to third-party APIs that affect digest delivery.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#14141e] mb-3">
              9. Intellectual property
            </h2>
            <p>
              arXiv papers are the intellectual property of their respective authors and are
              distributed under open-access licences. AI-generated summaries written to your
              Notion workspace are yours to use. The AI Digest codebase is open-source —
              see the{" "}
              <a
                href="https://github.com/sipandey/ai-digest-web"
                target="_blank"
                rel="noopener noreferrer"
                className="text-indigo-600 hover:underline"
              >
                GitHub repository
              </a>{" "}
              for licence details.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#14141e] mb-3">10. Changes to these terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the service after
              changes are posted constitutes acceptance of the revised terms. The &quot;Last
              updated&quot; date at the top of this page reflects the most recent revision.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#14141e] mb-3">
              11. Governing law
            </h2>
            <p>
              These terms are governed by the laws of India. Any disputes arising from your
              use of the service shall be subject to the exclusive jurisdiction of the courts
              of India.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#14141e] mb-3">12. Contact</h2>
            <p>
              Questions about these terms? Open an issue on{" "}
              <a
                href="https://github.com/sipandey/ai-digest-web"
                target="_blank"
                rel="noopener noreferrer"
                className="text-indigo-600 hover:underline"
              >
                GitHub
              </a>{" "}
              or reach out directly via the repository.
            </p>
          </section>

        </div>
      </main>

      <footer className="border-t border-gray-200 bg-white px-5 py-8 text-center flex items-center justify-center gap-6">
        <Link href="/" className="text-sm text-indigo-600 hover:underline">
          ← Back to AI Digest
        </Link>
        <Link href="/privacy" className="text-sm text-gray-400 hover:text-gray-600 transition-colors">
          Privacy Policy
        </Link>
      </footer>
    </div>
  );
}
